//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HairPlus.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        public AspNetUser()
        {
            this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
            this.Customers = new HashSet<Customer>();
            this.Customers1 = new HashSet<Customer>();
            this.Customers2 = new HashSet<Customer>();
            this.Customers3 = new HashSet<Customer>();
            this.Customers4 = new HashSet<Customer>();
            this.Customers5 = new HashSet<Customer>();
            this.CustomerPhotoes = new HashSet<CustomerPhoto>();
            this.CustomerPhotoes1 = new HashSet<CustomerPhoto>();
            this.CustomerPhotoes2 = new HashSet<CustomerPhoto>();
            this.CustomerPhotoes3 = new HashSet<CustomerPhoto>();
            this.CustomerPhotoes4 = new HashSet<CustomerPhoto>();
            this.CustomerPhotoes5 = new HashSet<CustomerPhoto>();
            this.Expenses = new HashSet<Expense>();
            this.Expenses1 = new HashSet<Expense>();
            this.Expenses2 = new HashSet<Expense>();
            this.Expenses3 = new HashSet<Expense>();
            this.Expenses4 = new HashSet<Expense>();
            this.Expenses5 = new HashSet<Expense>();
            this.HairLossSolutions = new HashSet<HairLossSolution>();
            this.HairLossSolutions1 = new HashSet<HairLossSolution>();
            this.HairLossSolutions2 = new HashSet<HairLossSolution>();
            this.HairLossSolutions3 = new HashSet<HairLossSolution>();
            this.HairLossSolutions4 = new HashSet<HairLossSolution>();
            this.HairLossSolutions5 = new HashSet<HairLossSolution>();
            this.Invoices = new HashSet<Invoice>();
            this.Invoices1 = new HashSet<Invoice>();
            this.Invoices2 = new HashSet<Invoice>();
            this.NonSurgicalPatients = new HashSet<NonSurgicalPatient>();
            this.NonSurgicalPatients1 = new HashSet<NonSurgicalPatient>();
            this.NonSurgicalPatients2 = new HashSet<NonSurgicalPatient>();
            this.NonSurgicalPatients3 = new HashSet<NonSurgicalPatient>();
            this.NonSurgicalPatients4 = new HashSet<NonSurgicalPatient>();
            this.NonSurgicalPatients5 = new HashSet<NonSurgicalPatient>();
            this.Patients = new HashSet<Patient>();
            this.Patients1 = new HashSet<Patient>();
            this.Patients2 = new HashSet<Patient>();
            this.Patients3 = new HashSet<Patient>();
            this.Patients4 = new HashSet<Patient>();
            this.Patients5 = new HashSet<Patient>();
            this.Reminders = new HashSet<Reminder>();
            this.Reminders1 = new HashSet<Reminder>();
            this.Reminders2 = new HashSet<Reminder>();
            this.Reminders3 = new HashSet<Reminder>();
            this.Reminders4 = new HashSet<Reminder>();
            this.Reminders5 = new HashSet<Reminder>();
            this.SurgicalPatients = new HashSet<SurgicalPatient>();
            this.SurgicalPatients1 = new HashSet<SurgicalPatient>();
            this.SurgicalPatients2 = new HashSet<SurgicalPatient>();
            this.SurgicalPatients3 = new HashSet<SurgicalPatient>();
            this.SurgicalPatients4 = new HashSet<SurgicalPatient>();
            this.SurgicalPatients5 = new HashSet<SurgicalPatient>();
            this.AspNetRoles = new HashSet<AspNetRole>();
        }
    
        public string Id { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<Customer> Customers1 { get; set; }
        public virtual ICollection<Customer> Customers2 { get; set; }
        public virtual ICollection<Customer> Customers3 { get; set; }
        public virtual ICollection<Customer> Customers4 { get; set; }
        public virtual ICollection<Customer> Customers5 { get; set; }
        public virtual ICollection<CustomerPhoto> CustomerPhotoes { get; set; }
        public virtual ICollection<CustomerPhoto> CustomerPhotoes1 { get; set; }
        public virtual ICollection<CustomerPhoto> CustomerPhotoes2 { get; set; }
        public virtual ICollection<CustomerPhoto> CustomerPhotoes3 { get; set; }
        public virtual ICollection<CustomerPhoto> CustomerPhotoes4 { get; set; }
        public virtual ICollection<CustomerPhoto> CustomerPhotoes5 { get; set; }
        public virtual ICollection<Expense> Expenses { get; set; }
        public virtual ICollection<Expense> Expenses1 { get; set; }
        public virtual ICollection<Expense> Expenses2 { get; set; }
        public virtual ICollection<Expense> Expenses3 { get; set; }
        public virtual ICollection<Expense> Expenses4 { get; set; }
        public virtual ICollection<Expense> Expenses5 { get; set; }
        public virtual ICollection<HairLossSolution> HairLossSolutions { get; set; }
        public virtual ICollection<HairLossSolution> HairLossSolutions1 { get; set; }
        public virtual ICollection<HairLossSolution> HairLossSolutions2 { get; set; }
        public virtual ICollection<HairLossSolution> HairLossSolutions3 { get; set; }
        public virtual ICollection<HairLossSolution> HairLossSolutions4 { get; set; }
        public virtual ICollection<HairLossSolution> HairLossSolutions5 { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<Invoice> Invoices1 { get; set; }
        public virtual ICollection<Invoice> Invoices2 { get; set; }
        public virtual ICollection<NonSurgicalPatient> NonSurgicalPatients { get; set; }
        public virtual ICollection<NonSurgicalPatient> NonSurgicalPatients1 { get; set; }
        public virtual ICollection<NonSurgicalPatient> NonSurgicalPatients2 { get; set; }
        public virtual ICollection<NonSurgicalPatient> NonSurgicalPatients3 { get; set; }
        public virtual ICollection<NonSurgicalPatient> NonSurgicalPatients4 { get; set; }
        public virtual ICollection<NonSurgicalPatient> NonSurgicalPatients5 { get; set; }
        public virtual ICollection<Patient> Patients { get; set; }
        public virtual ICollection<Patient> Patients1 { get; set; }
        public virtual ICollection<Patient> Patients2 { get; set; }
        public virtual ICollection<Patient> Patients3 { get; set; }
        public virtual ICollection<Patient> Patients4 { get; set; }
        public virtual ICollection<Patient> Patients5 { get; set; }
        public virtual ICollection<Reminder> Reminders { get; set; }
        public virtual ICollection<Reminder> Reminders1 { get; set; }
        public virtual ICollection<Reminder> Reminders2 { get; set; }
        public virtual ICollection<Reminder> Reminders3 { get; set; }
        public virtual ICollection<Reminder> Reminders4 { get; set; }
        public virtual ICollection<Reminder> Reminders5 { get; set; }
        public virtual ICollection<SurgicalPatient> SurgicalPatients { get; set; }
        public virtual ICollection<SurgicalPatient> SurgicalPatients1 { get; set; }
        public virtual ICollection<SurgicalPatient> SurgicalPatients2 { get; set; }
        public virtual ICollection<SurgicalPatient> SurgicalPatients3 { get; set; }
        public virtual ICollection<SurgicalPatient> SurgicalPatients4 { get; set; }
        public virtual ICollection<SurgicalPatient> SurgicalPatients5 { get; set; }
        public virtual ICollection<AspNetRole> AspNetRoles { get; set; }
    }
}
