//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HairPlus.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.CustomerPhotoes = new HashSet<CustomerPhoto>();
            this.CustomerPhotoes1 = new HashSet<CustomerPhoto>();
            this.CustomerPhotoes2 = new HashSet<CustomerPhoto>();
            this.CutomerHairLossSolutions = new HashSet<CutomerHairLossSolution>();
            this.Invoices = new HashSet<Invoice>();
            this.Invoices1 = new HashSet<Invoice>();
            this.Invoices2 = new HashSet<Invoice>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Gender { get; set; }
        public int Age { get; set; }
        public string Occupation { get; set; }
        public Nullable<int> TotalYearsOfHairLoss { get; set; }
        public string Address { get; set; }
        public string PhoneNo { get; set; }
        public string MobileNo { get; set; }
        public string EmailAddress { get; set; }
        public string HowYouKnowUs { get; set; }
        public int Stage { get; set; }
        public string Comment { get; set; }
        public Nullable<int> EstimatedAmount { get; set; }
        public Nullable<System.DateTime> VisitDateTime { get; set; }
        public int Priority { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> CustomerType { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
        public virtual AspNetUser AspNetUser3 { get; set; }
        public virtual AspNetUser AspNetUser4 { get; set; }
        public virtual AspNetUser AspNetUser5 { get; set; }
        public virtual ICollection<CustomerPhoto> CustomerPhotoes { get; set; }
        public virtual ICollection<CustomerPhoto> CustomerPhotoes1 { get; set; }
        public virtual ICollection<CustomerPhoto> CustomerPhotoes2 { get; set; }
        public virtual ICollection<CutomerHairLossSolution> CutomerHairLossSolutions { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<Invoice> Invoices1 { get; set; }
        public virtual ICollection<Invoice> Invoices2 { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Patient Patient1 { get; set; }
        public virtual Patient Patient2 { get; set; }
    }
}
