//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HairPlus.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int Id { get; set; }
        public System.DateTime BookingDateTime { get; set; }
        public int TotalAmount { get; set; }
        public int AdvanceAmount { get; set; }
        public int DiscountAmount { get; set; }
        public System.DateTime TreatmentDateTime { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
        public virtual AspNetUser AspNetUser3 { get; set; }
        public virtual AspNetUser AspNetUser4 { get; set; }
        public virtual AspNetUser AspNetUser5 { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Customer Customer1 { get; set; }
        public virtual Customer Customer2 { get; set; }
        public virtual NonSurgicalPatient NonSurgicalPatient { get; set; }
        public virtual NonSurgicalPatient NonSurgicalPatient1 { get; set; }
        public virtual NonSurgicalPatient NonSurgicalPatient2 { get; set; }
        public virtual SurgicalPatient SurgicalPatient { get; set; }
        public virtual SurgicalPatient SurgicalPatient1 { get; set; }
        public virtual SurgicalPatient SurgicalPatient2 { get; set; }
    }
}
